### ISSUE TITLE
Blog RSS reliative links

### ISSUE THREAD

**Issue by FUSAKLA** [grafana/grafana.org#67]
Hi, I like reading Grafana blog and want to know when you post something so I subscribed to your RSS channel. Everything works fine but one thing is annoying. The link to the post is not valid.

If you take a look at the RSS feed the link is relative url:
```xml
<item>
<title>GrafanaCon Recap: The State of TSDB</title>
<link>
/blog/2018/07/03/grafanacon-recap-the-state-of-tsdb/
</link>
<pubDate>Tue, 03 Jul 2018 00:00:00 +0000</pubDate>
<guid>
/blog/2018/07/03/grafanacon-recap-the-state-of-tsdb/
</guid>
<description>
From left to right: Erik Nordstrom – Timescale, Dan Cech – Graphite, Paul Dix – InfluxDB, Tom Wiklie – Prometheus At GrafanaCon EU, we gathered representatives of the Graphite, Prometheus, InfluxDB, and Timescale projects in the hopes of starting a spirited conversation about the current state of Time Series Databases. They didn’t disappoint! Here are a few highlights from the TSDB panel featuring Erik Nordstrom from Timescale, Dan Cech from Graphite, Paul Dix from InfluxDB, and Tom Wilkie from Prometheus, and moderated by Grafana Labs co-founder and CEO Raj Dutt.
</description>
</item>
```

It's missing the `http://grafana.com` prefix and RSS readers cannot handle that.

I looked at the Hugo RSS feed rendering and found this issue https://github.com/gohugoio/hugo/issues/725 but that was solved long time ago.

You have set 
https://github.com/grafana/grafana.org/blob/b84a43a546ef3963f509f26759b537b692cf2bc0/config.toml#L4
so this should expand the `.Permalink` in (the default Hugo RSS template)[https://gohugo.io/templates/rss/#the-embedded-rss-xml] with `baseURL` configuration option in the `config.toml`

The issue I suppose is 
https://github.com/grafana/grafana.org/blob/b84a43a546ef3963f509f26759b537b692cf2bc0/config.toml#L1

I'm not sure why you have the `localhost` there nevertheless I think it has no impact due to the (case sensitivity of Hugo toml configfile)[https://discourse.gohugo.io/t/config-no-longer-case-insensitive/153].

That could cause the `baseURL` to by empty and the canonicalization of `.Permalink` would prefix empty string thus the link would be still relative.

In that case could be setting `baseURL=http://grafana.com/` the solution. 

Still this is just theory I never used Hugo so maybe the issue is completely different.

But I'd definitely like to see this work it would ease my live a bit
And off course thanks for the blogging :)

**Comment by bulletfactory** [comment]
Thanks for submitting this issue - we are actively working on fixing a number of issues to make our blog better, so I'll make sure this is addressed.

Thanks!
Trent

**Comment by bulletfactory** [comment]
closed via #70

**Comment by bulletfactory** [comment]
Hi Martin - thanks for the update, I'll get this looked into and see if we
can get it resolved!

Trent

**Comment by FUSAKLA** [comment]
Looking at the 
https://github.com/grafana/grafana.org/blob/3a2efce6857824b8fa01268a9d3f7f0e2651e7dc/config.toml#L1

it was foxed to `baseUrl` but looking at the official docs it should be `baseURL`
https://gohugo.io/content-management/urls/#canonicalization

I'd give that a try maybe.

**Comment by thomas-riccardi** [comment]
bump

The issue is still present; the feed doesn't work in thunderbird for example.

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fgrafana.com%2Fblog%2Fblog%2Findex.xml

**Comment by bulletfactory** [comment]
closed via #100

**Comment by FUSAKLA** [comment]
:tada:  yesss this is great if it get's fixed! thanks :)
